# I name my Spring Boot application.
spring.application.name=topic1-1

# I use static HTML for this activity, so I do not require a Thymeleaf templates folder.
spring.thymeleaf.check-template-location=false